### ISSUE TITLE
Consider an integration with the ksonnet project

### ISSUE THREAD

**Issue by nikolay** [blendle/kubecrt#11]
https://github.com/ksonnet/ksonnet/issues/36#issue-268855430

**Comment by marcelser** [comment]
I think this should be closed as ksonnet development has ceised and their gitlab repos will be archived. It makes not sense to integrate anymore

**Comment by JeanMertz** [comment]
I should've replied a long time ago here, but was never really sure what to make of this. It makes sense to close this, thanks @marcelser.
