### ISSUE TITLE
Support partial templates

### ISSUE THREAD

**Issue by niels-s** [blendle/kubecrt#12]
Helm supports the use of golang partial template, it would be nice if kubecrt would support [this](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md#declaring-and-using-templates-with-define-and-template) as well.
This would enable us to spread large config files across multiple files so is easier to maintain them.

**Comment by JeanMertz** [comment]
@niels-s Unless I am misunderstanding your request, this is already supported. See this PR where I use this technique quite heavily:

https://github.com/blendle/charts/pull/24

**Comment by jurre** [comment]
I think the question is, can we also do this in a project where we use the chart, rather than in charts itself?

**Comment by niels-s** [comment]
^^ that @JeanMertz, for our prometheus deployment we would like to splits the alerting rules and sources for example into different templates grouped by something logical like for example kafka lag rules, k8s rules, http status/latency rules, ... but right now it's not possible I guess since we only pass 1 file to kubecrt we should have an option to indicate the template location

**Comment by JeanMertz** [comment]
Solved in https://github.com/blendle/kubecrt/pull/14
