### ISSUE TITLE
Can't tap from homebrew

### ISSUE THREAD

**Issue by vtelensky** [blendle/kubecrt#28]
When I do brew tap blendle/blendle on my M1 Mac I got:

Error: Invalid formula: /opt/homebrew/Library/Taps/blendle/homebrew-blendle/Formula/kubecrt.rb
kubecrt: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the blendle/blendle tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/blendle/homebrew-blendle/Formula/kubecrt.rb:11

Error: Invalid formula: /opt/homebrew/Library/Taps/blendle/homebrew-blendle/Formula/epp.rb
epp: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the blendle/blendle tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/blendle/homebrew-blendle/Formula/epp.rb:11
  
  
What can I do to resolve this?

**Comment by matejsoroka** [comment]
Same issue, Intel Mac

**Comment by oscaredel** [comment]
Yes, me too. I've been trying to solve it, but it will take some time to get familiar with this stuff. It is not my expertise. 

This change was needed: https://github.com/blendle/kubecrt/pull/27

But now I also need to update some formula's in https://github.com/blendle/homebrew-blendle. I think some homebrew requirements have changed since the last updates, next to that style fix.

**Comment by zhouying370481** [comment]
me too. 
i try install kubecrt  in centos7, but occur some errors ,as mentioned  above .

**Comment by oscaredel** [comment]
Ok, can you try again?

I did some updates to https://github.com/blendle/homebrew-blendle
First update the formulas in the blendle/blendle tap by running `brew update` and then install the formula's again.

If you encounter an error (like I did) you might need to reinstall everything:
```
brew uninstall FORMULAS
brew untap blendle/blendle

brew tap blendle/blendle
brew install kubecrt

# etc.
```

**Comment by oscaredel** [comment]
Just to be clear, maintenance on this tap/packages might stop entirely within a year, so if you depend on them, make sure to copy a version for yourself.

**Comment by oscaredel** [comment]
If anyone knows why brew sometimes wants to load this as a cask first, I'd be happy to know. :) 

```
Error: Failed to load cask: ./Formula/kubecrt.rb
Cask 'kubecrt' is unreadable: wrong constant name #<Class:0x00007ff52b32fd70>
Warning: Treating ./Formula/kubecrt.rb as a formula.
```
